codecov:
  branch: master
coverage:
  status:
    project:
      default:
        threshold: 5
    patch:
      default:
        target: 0%
  ignore:
    - "src/rtctools/_version.py"  # Exclude _version.py
comment:
  layout: "header, tree"