image: python:3.6

before_script:
  - pip install tox

stages:
  - build
  - test
  - deploy

# build
build:
  stage: build
  script:
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  tags:
    - docker

# test
.job_template: &unittests
  stage: test
  script:
    - tox -vv

py35:linux:
  <<: *unittests
  image: python:3.5-jessie
  variables:
    TOXENV: py35
  tags:
    - docker
    - linux

py36:linux:
  <<: *unittests
  image: python:3.6-jessie
  variables:
    TOXENV: py36
  tags:
    - docker
    - linux

# deploy
deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - pip install twine
    - twine upload -u $PYPI_USER -p $PYPI_PASSWORD dist/*
  only:
    - tags
  except:
    # Do not deploy tags that do not start with 2.
    - /^(?!2\.).*$
  tags:
    - docker
