image: python:3.8

before_script:
  - pip install tox

stages:
  - style
  - build
  - test
  - coverage
  - examples
  - deploy

# style
flake8:
  stage: style
  script:
    - tox -vv
  variables:
    TOXENV: flake8
  tags:
    - docker

# build
build:
  stage: build
  script:
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  tags:
    - docker

# test
.job_template: &unittests
  stage: test
  script:
    - tox -vv

py37:linux:
  <<: *unittests
  image: python:3.7-stretch
  variables:
    TOXENV: py37
  tags:
    - docker

py38:linux:
  <<: *unittests
  image: python:3.8-buster
  variables:
    TOXENV: py38
  tags:
    - docker

# run examples (only for tags)
.job_template: &examples
  stage: examples
  script:
    - tox -vv
  only:
    - tags
  tags:
    - docker

examples37:linux:
  <<: *examples
  image: python:3.7-stretch
  variables:
    TOXENV: examples37

examples38:linux:
  <<: *examples
  image: python:3.8-buster
  variables:
    TOXENV: examples38

# coverage
coverage:
  stage: coverage
  script:
    - tox -vv
    - pip install codecov
    - codecov --token=$CODECOV_TOKEN
  variables:
    TOXENV: coverage
  tags:
    - docker

# deploy
deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - pip install twine
    - twine upload -u $PYPI_USER -p $PYPI_PASSWORD dist/*
  only:
    # Only deploy refs that start with "2."
    - /^2\..*$/
  except:
    # If a branch happens to start with "2.", skip it as we only want to
    # deploy tags.
    - branches
  tags:
    - docker
