image: python:3-jessie

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - pip wheel sdist bdist_wheel
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  tags:
    - docker
    - python3

test:
  stage: test
  dependencies:
    - build
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install dist/*.whl
    - pip install nose
    - cd tests
    - python -m nose
  tags:
    - docker
    - python3

deploy:
  stage:
    - deploy
  dependencies:
    - test
  script:
    - pip install twine
    - twine upload --repository-url https://test.pypi.org/legacy/ -u %PYPI_USER% -p %PYPI_PASSWORD% dist/*
  only:
    - tags
  except:
    # Do not deploy tags that do not start with 2.2.
    - /^(?!2\.2\.).*$
  tags:
    - docker
    - python3
