image: python:3-jessie

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  tags:
    - docker
    - python3

test:
  stage: test
  dependencies:
    - build
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install git+https://github.com/pymoca/pymoca.git
    - pip install dist/*.whl
    - pip install nose
    - cd tests
    - python -m nose
  tags:
    - docker
    - python3
