exclude: |
  (?x)^(
    src/rtctools/_version\.py|
    versioneer.py
  )$
repos:
  # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.9.1
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies:
          [flake8-bugbear==23.1.20, flake8-comprehensions==3.10, flake8-import-order==0.18]
