name: "Setup Python Environment"
description: "Sets up Python environment with uv package manager"

inputs:
  uv-version:
    description: "Version of uv to install"
    required: false
    default: "0.7.9"
  dependency-groups:
    description: "Space-separated list of dependency groups to install (e.g. 'deploy tests')"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Install uv
      # Pinned to commit SHA for security (v7.1.0)
      # Deltares GitHub FAQ: https://publicwiki.deltares.nl/spaces/GIT/pages/279642305/GitHub#Pages-FAQ
      # Vetted: 2025-01-14 | Update regularly and review changelog
      uses: astral-sh/setup-uv@3259c6206f993105e3a61b142c2d97bf4b9ef83d
      with:
        version: ${{ inputs.uv-version }}
        enable-cache: true
        cache-dependency-glob: "uv.lock"
        # Used only for API rate limiting, not for authentication (see security documentation)
        github-token: ${{ github.token }}

    - name: Install dependencies
      shell: bash
      run: |
        CMD="uv sync --frozen --no-dev"
        if [[ -n "${{ inputs.dependency-groups }}" ]]; then
          for group in ${{ inputs.dependency-groups }}; do
            CMD="$CMD --group $group"
          done
        fi
        $CMD
